apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-training
  name: k8s-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-training
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-training
    spec:
      containers:
      - image: docker.io/devopsguru91/test-jenkins-image:latest
        name: k8s-training
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-training
  name: k8s-training
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: k8s-training
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-training
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
spec:
  rules:
  - http:
      paths:
      - path: /k8s-training
        backend:
          serviceName: k8s-training
          servicePort: 80
